"""
Converts results from the questionnaire into a more structured and useful format.
Usage: 
    python questionnaire_cleaning.py
"""

import pandas as pd

# ==========================================
# LOAD ORIGINAL FILE
# ==========================================

df = pd.read_excel("Questionnaire_answers.xlsx")

# ==========================================
# EXACT COLUMN NAMES
# ==========================================

AB_COLUMN = (
    "Please select the option that appears first. "
    "This will be used to redirect you to one of two sets of questions."
)

BASE_COLUMNS = [
    "Marca de temps",
    "Gender",
    "Occupation",
    "Years of experience with coding "
]

# Each question block has 6 columns
QUESTION_FIELDS = [
    "Correct",
    "Full_Use",
    "Natural",
    "Hallucination",
    "Prediction",
    "Remarks"
]

# ==========================================
# FUNCTION MAPPINGS
# IMPORTANT:
# GROUP A QUESTIONS
# ==========================================

GROUP_A = [
    {"id": 72463, "ground_truth": "Human-written"},
    {"id": 164057, "ground_truth": "Human-written"},
    {"id": 96031, "ground_truth": "Generated"},
    {"id": 197753, "ground_truth": "Human-written"},
    {"id": 96331, "ground_truth": "Generated"},
    {"id": 53398, "ground_truth": "Generated"},
    {"id": 243818, "ground_truth": "Human-written"},
    {"id": 66203, "ground_truth": "Generated"},
    {"id": 39110, "ground_truth": "Human-written"},
    {"id": 34913, "ground_truth": "Generated"},
]

# ==========================================
# GROUP B QUESTIONS
# ==========================================

GROUP_B = [
    {"id": 72463, "ground_truth": "Generated"},
    {"id": 164057, "ground_truth": "Generated"},
    {"id": 96031, "ground_truth": "Human-written"},
    {"id": 197753, "ground_truth": "Generated"},
    {"id": 96331, "ground_truth": "Human-written"},
    {"id": 53398, "ground_truth": "Human-written"},
    {"id": 243818, "ground_truth": "Generated"},
    {"id": 66203, "ground_truth": "Human-written"},
    {"id": 39110, "ground_truth": "Generated"},
    {"id": 34913, "ground_truth": "Human-written"},
]

# ==========================================
# FIND WHERE QUESTION BLOCKS START
# ==========================================

ab_index = df.columns.get_loc(AB_COLUMN)

# Group A responses start immediately
group_a_start = len(BASE_COLUMNS)

# Group B responses start AFTER AB column
group_b_start = ab_index + 1

# ==========================================
# BUILD NORMALIZED DATASET
# ==========================================

all_rows = []

for _, row in df.iterrows():

    participant = {
        "Marca de temps": row["Marca de temps"],
        "Gender": row["Gender"],
        "Occupation": row["Occupation"],
        "Years of experience with coding ":
            row["Years of experience with coding "],
        "AB_Group": row[AB_COLUMN]
    }

    # --------------------------------------
    # GROUP A PARTICIPANTS
    # --------------------------------------

    if row[AB_COLUMN] == "A":

        for i, func in enumerate(GROUP_A):

            offset = group_a_start + (i * 6)

            all_rows.append({

                **participant,

                "Function_ID": func["id"],
                "Ground_Truth": func["ground_truth"],

                "Does the description correctly describe what the function actually does?":
                    row.iloc[offset],

                "Does the description fully describe the code's use?":
                    row.iloc[offset + 1],

                "Is the docstring natural, clear, and well written?":
                    row.iloc[offset + 2],

                "Does the docstring mention behavior not present in the code?":
                    row.iloc[offset + 3],

                "Do you believe this description is human-written or generated by an LLM?":
                    row.iloc[offset + 4],

                "Additional remarks":
                    row.iloc[offset + 5]
            })

    # --------------------------------------
    # GROUP B PARTICIPANTS
    # --------------------------------------

    elif row[AB_COLUMN] == "B":

        for i, func in enumerate(GROUP_B):

            offset = group_b_start + (i * 6)

            all_rows.append({

                **participant,

                "Function_ID": func["id"],
                "Ground_Truth": func["ground_truth"],

                "Does the description correctly describe what the function actually does?":
                    row.iloc[offset],

                "Does the description fully describe the code's use?":
                    row.iloc[offset + 1],

                "Is the docstring natural, clear, and well written?":
                    row.iloc[offset + 2],

                "Does the docstring mention behavior not present in the code?":
                    row.iloc[offset + 3],

                "Do you believe this description is human-written or generated by an LLM?":
                    row.iloc[offset + 4],

                "Additional remarks":
                    row.iloc[offset + 5]
            })

# ==========================================
# CREATE DATAFRAME
# ==========================================

normalized_df = pd.DataFrame(all_rows)

# ==========================================
# SPLIT BY GROUND TRUTH
# ==========================================

human_df = normalized_df[
    normalized_df["Ground_Truth"] == "Human-written"
]

generated_df = normalized_df[
    normalized_df["Ground_Truth"] == "Generated"
]

# ==========================================
# SAVE OUTPUT
# ==========================================

with pd.ExcelWriter(
    "grouped_responses_fixed.xlsx",
    engine="openpyxl"
) as writer:

    normalized_df.to_excel(
        writer,
        sheet_name="All_Responses",
        index=False
    )

    human_df.to_excel(
        writer,
        sheet_name="Human_Written",
        index=False
    )

    generated_df.to_excel(
        writer,
        sheet_name="Generated",
        index=False
    )

print("Done: grouped_responses_fixed.xlsx")
